[package]
name = "remote_mount"
version = "0.1.0"
edition = "2021"
authors = ["Blooym"]

[features]
default = ["protocol-full"]
protocol-full = ["protocol-sshfs"]
protocol-sshfs = []

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
async-trait = "0.1.71"
