[package]
name = "remote-mount"
version = "0.3.0"
edition = "2021"
authors = ["Blooym"]
license = "AGPL-3.0-only"
repository = "https://github.com/Blooym/Hermes"

[features]
default = []
protocols-sshfs = ["which", "tokio"]

[dependencies.anyhow]
version = "1.0.75"

[dependencies.async-trait]
version = "0.1.73"

[dependencies.tokio]
version = "1.32.0"
features = ["full"]
optional = true

[dependencies.which]
version = "4.4.0"
optional = true

[dependencies.log]
version = "0.4.20"
